<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CORREGIDO</name>
   <tag></tag>
   <elementGuidId>5004e0ae-ca1a-43ad-ba7d-2cb12adad0a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-estadoConsignado-result-o042-9007']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-estadoConsignado-result-o042-9007</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e28ec74b-e008-47c4-b59d-48abeb49f40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>4473619c-962b-44df-a363-9be76f66e4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-o042-9007</value>
      <webElementGuid>c0691210-9adc-4934-af8f-6825757bdfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d4d535cb-3a42-4dcd-883e-bebad5558a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb39d5f6-7b5c-4102-9974-f6ced83615ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-o042-9007</value>
      <webElementGuid>7c867e3b-ad4b-4c98-aba7-fd3599992a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        CORREGIDO                                                    </value>
      <webElementGuid>023a466b-ba1b-4a0a-9548-40849229d715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-estadoConsignado-result-o042-9007&quot;)</value>
      <webElementGuid>6ee14f2e-548d-47cf-b863-31065cddb92c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-estadoConsignado-result-o042-9007']</value>
      <webElementGuid>3023d65b-e5b4-4c75-8e3d-45ff754b5831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-estadoConsignado-results']/li[4]</value>
      <webElementGuid>f469852e-a790-4a22-9339-c03ac13e5353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO ERROR'])[2]/following::li[1]</value>
      <webElementGuid>9dd0cf89-5c0d-477f-ad12-bf32baecf3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO OK'])[96]/following::li[2]</value>
      <webElementGuid>b8d2ffd2-c909-4fa8-84b1-f2cbd47370b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[4]</value>
      <webElementGuid>7781c9f7-f20e-4f3e-9e17-a37b848f51a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-estadoConsignado-result-o042-9007' and (text() = '
                                                        CORREGIDO                                                    ' or . = '
                                                        CORREGIDO                                                    ')]</value>
      <webElementGuid>8003e2d6-c5f4-45b9-86f2-af7c30f52a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
