<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DNI NO MATCH</name>
   <tag></tag>
   <elementGuidId>07f54163-e734-4053-a874-ef3d5c97c9a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-motivo-result-zck5-9013']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-motivo-result-zck5-9013</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a4393c59-cd01-4979-abd5-b7a925aebbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>d64acd4b-ad8a-432f-aaf9-96b556fa3493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-motivo-result-zck5-9013</value>
      <webElementGuid>e22ce226-b51a-4b30-b4cf-ac7789b8dc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6351a941-71b5-447e-afc4-d405ada5bb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1064439c-7690-4c7e-b233-ad6df641ffb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-motivo-result-zck5-9013</value>
      <webElementGuid>21259f05-a728-46a3-bbb5-c2f5e6d815da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        DNI NO MATCH                                                    </value>
      <webElementGuid>4e280524-0054-4e12-91ad-5029e03bf826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-motivo-result-zck5-9013&quot;)</value>
      <webElementGuid>95e7b440-a244-4ab4-8f8d-3e4e4bb8ad36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-motivo-result-zck5-9013']</value>
      <webElementGuid>9e0a6732-d3a4-48e4-a322-29c779c7b302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-motivo-results']/li[5]</value>
      <webElementGuid>fd1ffdd0-7bf8-4556-99e0-a615540494b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DNI NO EXISTE'])[2]/following::li[1]</value>
      <webElementGuid>82bd3516-1cde-42c0-a170-a300b051af8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC NO MATCH'])[2]/following::li[2]</value>
      <webElementGuid>e6c88925-4ea9-4d8a-87b3-a0bb8325bb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]</value>
      <webElementGuid>57727ae6-21de-472b-b320-78b70ede8244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-motivo-result-zck5-9013' and (text() = '
                                                        DNI NO MATCH                                                    ' or . = '
                                                        DNI NO MATCH                                                    ')]</value>
      <webElementGuid>460ae995-4c6f-4a23-871d-0620935bd1c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
