<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_RUC NO EXISTE</name>
   <tag></tag>
   <elementGuidId>335d3dac-597a-44e3-a991-0ba715d2fd59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-motivo-result-n1b1-9010']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-motivo-result-n1b1-9010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>15840909-5759-412d-9f33-3893dab27fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>eb73d7f1-7205-4383-aa69-f422a1377010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-motivo-result-n1b1-9010</value>
      <webElementGuid>fccd8758-74c7-4e2c-a9a1-b9b7cd7ef733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>df69ddff-a7f0-4dc6-82a7-d492a84895b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>23dcd6f8-e2d0-45f5-be5a-d996c96231cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-motivo-result-n1b1-9010</value>
      <webElementGuid>604bdb5e-b7cd-4f96-a303-f2e2e098fcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        RUC NO EXISTE                                                    </value>
      <webElementGuid>c091e7c2-590c-4df6-8855-2b9bca70a213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-motivo-result-n1b1-9010&quot;)</value>
      <webElementGuid>7b5956d9-52f2-4e63-a074-77093a1a634e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3e7b86b7-e892-4a07-a727-bd56d723a99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>64d700e4-40dd-4a43-b435-809ae3721e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-motivo-result-yslj-9010</value>
      <webElementGuid>41d96517-7ccd-4b77-8696-0f19528c1f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9eeabf70-8b85-4779-8a97-275bdf98e970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9313a3d1-2306-4692-ad4e-01cf727fae99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-motivo-result-yslj-9010</value>
      <webElementGuid>6d8ebd5c-2e76-4a51-820c-3eedf3b844cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        RUC NO EXISTE                                                    </value>
      <webElementGuid>fa5d9c00-24dd-470a-8483-eff7fac26444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-motivo-result-yslj-9010&quot;)</value>
      <webElementGuid>6e2dbc24-53bd-470d-a31d-7d88c68c8b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-motivo-result-n1b1-9010']</value>
      <webElementGuid>b6a27dba-5800-4d5c-b0ba-fad16fcaf0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-motivo-results']/li[2]</value>
      <webElementGuid>ac66bfaa-ff69-4eaf-bcfe-c386ac2373dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC NO ACTIVO'])[3]/following::li[1]</value>
      <webElementGuid>ca678d73-eff9-4320-b781-834247bc94a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-motivo-result-n1b1-9010', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>d6563236-455e-4028-999e-19ffc8099b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC NO MATCH'])[2]/preceding::li[1]</value>
      <webElementGuid>38394cb7-4936-489c-bda7-351fa6a14ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DNI NO EXISTE'])[2]/preceding::li[2]</value>
      <webElementGuid>0f4f572d-3c28-42ed-b6cc-a3ba4c3deaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[2]</value>
      <webElementGuid>50499d16-9635-456f-ad6e-4fb3a310f028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-motivo-result-n1b1-9010' and (text() = '
                                                        RUC NO EXISTE                                                    ' or . = '
                                                        RUC NO EXISTE                                                    ')]</value>
      <webElementGuid>7a209930-75aa-4e11-aebf-b2b41047b639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-motivo-result-yslj-9010']</value>
      <webElementGuid>e58167eb-016f-4a4a-b7f8-9c90d1fb10f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC NO ACTIVO'])[5]/following::li[1]</value>
      <webElementGuid>5bbc640a-96bc-4b0b-a3ab-b60b3acd5902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-motivo-result-yslj-9010', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>efc3e28b-2fad-4280-864e-3a1b6d4a30c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-motivo-result-yslj-9010' and (text() = '
                                                        RUC NO EXISTE                                                    ' or . = '
                                                        RUC NO EXISTE                                                    ')]</value>
      <webElementGuid>fecdb9a2-d780-4073-a9f8-fd1814eff49c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
