<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_REGISTRADO</name>
   <tag></tag>
   <elementGuidId>58d85972-7494-4c7f-a1b7-43acaa446fd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-estadoConsignado-result-82ut-9004']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-estadoConsignado-result-82ut-9004</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a1e28c68-b8d1-4d4a-ada3-ebba97b010a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option</value>
      <webElementGuid>6b5bda5f-0e9c-462f-9c9a-c793015c4a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-82ut-9004</value>
      <webElementGuid>af8d7985-ff7b-43fe-9f89-12323498102c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>16a535e0-61d8-4c63-ab91-c6aa8b517cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>96755d43-76b7-4f7b-b72b-6b5ef6de3592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-82ut-9004</value>
      <webElementGuid>24006fdd-1d2c-478d-814d-1bf901ec6946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        REGISTRADO                                                    </value>
      <webElementGuid>bc62a42d-b220-4c2c-be9a-8bf6feb6f925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-estadoConsignado-result-82ut-9004&quot;)</value>
      <webElementGuid>ecc06b69-e66a-414c-b3c2-de71659956a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5d01a51f-0518-4c94-86ef-ec821368734b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>e177c3cf-384a-484f-9157-51ae46e881ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-dhml-9004</value>
      <webElementGuid>ae7a4235-953e-4065-b978-b98d6b58bf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6ae68996-af1e-4283-afd0-42d865fa3197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e76f212-2b74-4fd6-8f5a-28ba360f17aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-dhml-9004</value>
      <webElementGuid>e004ed2a-bd89-4488-bcec-bdc4185033dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        REGISTRADO                                                    </value>
      <webElementGuid>e1f1befd-f206-495d-91a7-c7daf8b2c8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-estadoConsignado-result-dhml-9004&quot;)</value>
      <webElementGuid>ec755f09-8ba4-41e0-870c-a84037617d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-estadoConsignado-result-82ut-9004']</value>
      <webElementGuid>d44ddc56-7621-41f2-86fe-aacd241c3ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-estadoConsignado-results']/li</value>
      <webElementGuid>4874ce28-ee0e-40e1-b983-15fb5662d61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-estadoConsignado-result-c59y-9005', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>73d131a9-6cd2-4ab9-b429-db9aa699bb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrar'])[1]/following::li[1]</value>
      <webElementGuid>498557d8-28ea-4c1f-8ef1-5ce94dce74ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO OK'])[96]/preceding::li[1]</value>
      <webElementGuid>aa74d7fc-c53c-4941-8c08-95e91ec162ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO ERROR'])[3]/preceding::li[2]</value>
      <webElementGuid>f56004a7-7f59-4e3b-9770-0e722a6a3b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>69340238-14bf-4cee-9780-a86fdd119a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-estadoConsignado-result-82ut-9004' and (text() = '
                                                        REGISTRADO                                                    ' or . = '
                                                        REGISTRADO                                                    ')]</value>
      <webElementGuid>315f9ddf-7399-46a0-ad1d-c76a47e45642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-estadoConsignado-result-dhml-9004']</value>
      <webElementGuid>a98dc546-e3e9-460d-8dcd-bcf8d312a348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-estadoConsignado-result-dhml-9004', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>57dac1fc-e338-4397-b24f-b7ca94fe6ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO OK'])[100]/preceding::li[1]</value>
      <webElementGuid>67a772c1-bd33-49e2-a856-ac4c510ad66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO ERROR'])[7]/preceding::li[2]</value>
      <webElementGuid>3734dc64-782c-4ba2-a037-c8dcb3720852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-estadoConsignado-result-dhml-9004' and (text() = '
                                                        REGISTRADO                                                    ' or . = '
                                                        REGISTRADO                                                    ')]</value>
      <webElementGuid>a1a0d724-4d2d-4b58-8861-af0ef7aa93d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
