<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_VALIDADO ERROR_1</name>
   <tag></tag>
   <elementGuidId>adae43ee-7d54-4ff1-9472-6425debd1541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-estadoConsignado-result-jyfl-9006']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-estadoConsignado-result-jyfl-9006</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8fcae7bf-795a-441c-a930-0e5c22bef74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>3471fc91-06fd-4926-a6a5-f33d9e51236c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-jyfl-9006</value>
      <webElementGuid>49bc813e-04ff-43e6-943c-43e35c401608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f8798e71-b109-4f26-9a9e-2c2b356cac24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f63b1df8-84dc-4a65-9d79-741ce7a935d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-jyfl-9006</value>
      <webElementGuid>9cba7d59-7096-45de-b294-f56a05e19253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        VALIDADO ERROR                                                    </value>
      <webElementGuid>64c6e109-8a47-47a0-ae90-2858c857e75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-estadoConsignado-result-jyfl-9006&quot;)</value>
      <webElementGuid>46c10cd6-5a89-4caf-b437-acf01249e106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-estadoConsignado-result-jyfl-9006']</value>
      <webElementGuid>3799b94e-2be5-4f35-bb11-2fc17f1ed17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-estadoConsignado-results']/li[3]</value>
      <webElementGuid>e7ce6332-3daa-41b9-8c8f-2793dec65b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO OK'])[96]/following::li[1]</value>
      <webElementGuid>1483ce75-7d0f-450d-a4de-c37d483619a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRADO'])[2]/following::li[2]</value>
      <webElementGuid>5db99217-ab51-4239-9568-08e67cb9127b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CORREGIDO'])[15]/preceding::li[1]</value>
      <webElementGuid>993a2b5a-952d-4661-924f-0e64491f2ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[3]</value>
      <webElementGuid>c6508c88-a3c3-4ce1-a8ee-b40cd5dba85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-estadoConsignado-result-jyfl-9006' and (text() = '
                                                        VALIDADO ERROR                                                    ' or . = '
                                                        VALIDADO ERROR                                                    ')]</value>
      <webElementGuid>cbfab088-da67-4f55-a265-f70e2f95f318</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
