<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_VALIDADO_OK</name>
   <tag></tag>
   <elementGuidId>686342f4-3821-47d3-8f36-e5b54c747a0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-estadoConsignado-result-c59y-9005']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-estadoConsignado-result-c59y-9005</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>82bcd20e-6f99-48fa-9c56-c567a8d5e6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>b93a8b6a-be2f-4982-aba2-9e423cc70acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-c59y-9005</value>
      <webElementGuid>7a94b2b2-2466-4b0f-8661-9eaefb3e20c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7ec9d356-b3a6-4c58-98ba-ac9145da20dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>631d9f13-53ca-4b21-abc7-10b40ea79eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-c59y-9005</value>
      <webElementGuid>9f478263-080e-492d-a10d-5afcd2778d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        VALIDADO OK                                                    </value>
      <webElementGuid>4829f2ba-42a0-4fc8-b3f6-98543ca1a1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-estadoConsignado-result-c59y-9005&quot;)</value>
      <webElementGuid>df4ac41e-65ef-419e-9b7b-3e5c466cbfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>85a3ef58-cf5e-41bb-99f0-8461a5856c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>a2512572-e062-4540-a081-cc9852b83a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-q3kd-9005</value>
      <webElementGuid>b12be275-3172-4f95-8198-23bbacc36e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3aba7a87-879d-4d31-ad0a-ec4bc73b293b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a87d31b9-2a02-495d-98bd-2364ec59a4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-q3kd-9005</value>
      <webElementGuid>76a50db7-5a18-464f-8eb7-66356a8fd83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        VALIDADO OK                                                    </value>
      <webElementGuid>45651c42-5ad1-40d7-af9d-4e22891f9ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-estadoConsignado-result-q3kd-9005&quot;)</value>
      <webElementGuid>d89dc623-5b5f-41cc-91a8-6ca4a27c04ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3b226a85-1899-49ae-9539-e9241b69a423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>0aa151ed-693d-4698-bda3-8a16c6a5756a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-ezzv-9005</value>
      <webElementGuid>819cf2ec-6e42-4d20-9c3a-c7469a2881c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>647bc634-3b49-4ee4-9f54-5a1e71f188f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>245f9b86-fe2c-4ac7-aa62-bb2cc9dfabcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-ezzv-9005</value>
      <webElementGuid>95ddf9f9-a2c3-4f42-82f2-5e21747f69e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        VALIDADO OK                                                    </value>
      <webElementGuid>9955392d-c2e4-461d-bb48-6887f3420156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-estadoConsignado-result-ezzv-9005&quot;)</value>
      <webElementGuid>c169e275-78ba-43a7-911f-dc59bbec8900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-estadoConsignado-result-c59y-9005']</value>
      <webElementGuid>35fe9b50-3da2-48d1-ba80-bd30cfc7ede4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-estadoConsignado-results']/li[2]</value>
      <webElementGuid>af9efab7-cecf-457b-8b44-6d63505ce4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRADO'])[2]/following::li[1]</value>
      <webElementGuid>b4927a19-67ef-4de3-96e2-0b13b309c881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-estadoConsignado-result-c59y-9005', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>9c5e7725-89a2-4efb-a412-7f54c1706819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO ERROR'])[3]/preceding::li[1]</value>
      <webElementGuid>78d8bd45-fa19-4d21-93a1-66cc5201e6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CORREGIDO'])[15]/preceding::li[2]</value>
      <webElementGuid>d4411af2-9e0e-4646-be72-d088902c281a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[2]</value>
      <webElementGuid>880dc8f4-ef2f-494f-b900-9ee72642f818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-estadoConsignado-result-c59y-9005' and (text() = '
                                                        VALIDADO OK                                                    ' or . = '
                                                        VALIDADO OK                                                    ')]</value>
      <webElementGuid>102ef41b-20d1-4cd0-b9ee-b7cbba9f67b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-estadoConsignado-result-q3kd-9005']</value>
      <webElementGuid>58cc1592-868b-41b1-80e8-7438bdd6c780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-estadoConsignado-result-q3kd-9005', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>6ff8335b-1883-47ae-9cc9-53bc5b4370c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-estadoConsignado-result-q3kd-9005' and (text() = '
                                                        VALIDADO OK                                                    ' or . = '
                                                        VALIDADO OK                                                    ')]</value>
      <webElementGuid>37c8032e-d0a8-4e1e-ae59-46a3b9cac7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-estadoConsignado-result-ezzv-9005']</value>
      <webElementGuid>e9928051-1298-4b9b-85c3-22243a98cbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-estadoConsignado-result-ezzv-9005', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>6e31350e-0b1e-4e6a-8c0d-f012a2f3c28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO ERROR'])[2]/preceding::li[1]</value>
      <webElementGuid>071434c5-1e81-4277-a81d-9f88db314afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CORREGIDO'])[2]/preceding::li[2]</value>
      <webElementGuid>b98d0d3b-a1f3-48fe-9526-97591479ca4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-estadoConsignado-result-ezzv-9005' and (text() = '
                                                        VALIDADO OK                                                    ' or . = '
                                                        VALIDADO OK                                                    ')]</value>
      <webElementGuid>d23cd965-8c83-4b8a-b774-9fbb2513eabb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
