<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_santoro</name>
   <tag></tag>
   <elementGuidId>38a906a3-823d-4544-9936-8270426f1ab8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tableReporte']/tbody/tr[3]/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e1dbb145-998c-4385-9268-55a2d2aacafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-middle</value>
      <webElementGuid>7b7582d2-9564-4f56-b35c-18585e6dd909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>santoro   </value>
      <webElementGuid>d0b315b8-b22d-4046-a1b0-55029abfc7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableReporte&quot;)/tbody[1]/tr[3]/td[@class=&quot;align-middle&quot;]</value>
      <webElementGuid>d7232be7-c5b6-4870-b427-a8604fe94505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableReporte']/tbody/tr[3]/td[4]</value>
      <webElementGuid>8e563cf9-4765-40a3-b82f-d42dc5ef1c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[36]/following::td[5]</value>
      <webElementGuid>23c33967-a2fb-402e-98be-d4d5453c7487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DSR'])[3]/following::td[6]</value>
      <webElementGuid>591ecfa7-9c7e-4595-8b15-97b0461dfb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MLPE0117935E'])[1]/preceding::td[1]</value>
      <webElementGuid>ab27bb89-e890-4ef0-a2d3-4f176439552b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CORREGIDO'])[2]/preceding::td[3]</value>
      <webElementGuid>211b03f5-9022-42bd-94df-859478789d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[3]/td[4]</value>
      <webElementGuid>d45e8f27-ba8d-4e8f-a758-b41cecaed0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'santoro   ' or . = 'santoro   ')]</value>
      <webElementGuid>9016cfd5-f538-4448-8538-c8dfe6a6be50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
