<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_JVILCA</name>
   <tag></tag>
   <elementGuidId>9aeaabd1-4a67-4c6c-84ea-d28eb0970e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frm_sendDatos']/div/div[2]/div/div/span/span/span/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.select2-selection__rendered</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>1620799c-b7de-4567-86de-d8ae47fd44de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>4d0b5280-7daa-4f7f-80ce-38e37b1c3afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>××
                                                        JVILCA                                                        </value>
      <webElementGuid>70846664-03b8-4f77-9b12-b6de95b18e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm_sendDatos&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-7&quot;]/span[@class=&quot;select2 select2-container select2-container--default select2-container--focus&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--multiple&quot;]/ul[@class=&quot;select2-selection__rendered&quot;]</value>
      <webElementGuid>1d8f436a-bd7b-4394-aee8-e3eb0b591707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_sendDatos']/div/div[2]/div/div/span/span/span/ul</value>
      <webElementGuid>d04001df-2a23-45a8-ad61-6af37b489284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liquidador:'])[1]/following::ul[1]</value>
      <webElementGuid>961d06ff-cce7-4d74-91a2-f59c641197e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fin'])[1]/following::ul[1]</value>
      <webElementGuid>5dbd68c9-b377-4799-98ce-06ad2b2271cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>0e20bb71-e25b-4fee-92d4-7968d0c2d6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = '××
                                                        JVILCA                                                        ' or . = '××
                                                        JVILCA                                                        ')]</value>
      <webElementGuid>08ca5a74-124e-46b2-afa3-2570389d95bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
