<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intranet</name>
   <tag></tag>
   <elementGuidId>1eeee743-e586-4360-85ac-7fdf9e2ca65a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Intranet')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f4186dac-0403-4c5c-bcac-c5660add7b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.olva.pe/intranet_compras</value>
      <webElementGuid>23843cde-751b-4c64-851b-8785fe883b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intranet</value>
      <webElementGuid>ad7cc003-9110-4cd9-a29e-48d2ab4fcb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 order-md-2 mb-6&quot;]/ul[@class=&quot;list-group mb-3&quot;]/li[@class=&quot;list-group-item d-flex justify-content-between lh-condensed&quot;]/div[1]/h6[1]/a[1]</value>
      <webElementGuid>105010e4-fdd5-49e0-b260-2d8b8ad32513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intranet')]</value>
      <webElementGuid>207b5a05-a85b-4d22-9125-85457492e754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agentes Internacionales'])[1]/following::a[1]</value>
      <webElementGuid>f4ae701a-bcdb-442a-b3ba-f85322bf7b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Links'])[1]/following::a[2]</value>
      <webElementGuid>847e820f-b72d-4f9b-8b8e-b5a4483feb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicios Premium'])[1]/preceding::a[1]</value>
      <webElementGuid>5b509c96-b325-425f-837f-510cc36d8c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BBVA Premios'])[1]/preceding::a[2]</value>
      <webElementGuid>da74fc25-2f89-40a6-b7f8-3ea41af94e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intranet']/parent::*</value>
      <webElementGuid>c858f437-db4f-473a-9012-2b0472aa41c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.olva.pe/intranet_compras')]</value>
      <webElementGuid>80a80698-f77c-432f-aa71-463a559dd2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/h6/a</value>
      <webElementGuid>137f8bee-cbed-4185-aa61-79fd8668a9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.olva.pe/intranet_compras' and (text() = 'Intranet' or . = 'Intranet')]</value>
      <webElementGuid>6470d7d5-9293-4daa-912e-d14b3bbd17dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
