<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buscar</name>
   <tag></tag>
   <elementGuidId>832811a0-6ec3-43a8-97ff-6609601becd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnBuscarGuias</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnBuscarGuias']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5131f566-7695-42a1-a92e-f7ef259f736c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>924ff282-a764-4b2d-a5c5-4422ab712ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-md</value>
      <webElementGuid>c1a2fb4c-a7ba-4873-9f90-2bcccb548c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnBuscarGuias</value>
      <webElementGuid>e171a3b7-ad62-4a16-be70-e03164368ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>4744195f-ea67-4ca5-855e-da295db58191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnBuscarGuias&quot;)</value>
      <webElementGuid>f353c62c-151e-4aae-864e-6df2bbf37f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder/iframe_Abrir_iframe_principal</value>
      <webElementGuid>495e6f84-5737-4974-a6ee-ee78122945dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnBuscarGuias']</value>
      <webElementGuid>9b309b91-a530-404b-8839-69828ec1123b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_sendDatos']/div/div[5]/button</value>
      <webElementGuid>52aa4e8d-b731-4388-b138-e3d527c6c932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guia Hija'])[1]/following::button[1]</value>
      <webElementGuid>2e377f93-3acc-4199-954d-ba192c125882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guia Master'])[1]/following::button[1]</value>
      <webElementGuid>d1baa2a6-4211-4184-9f13-d32152f689a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liquidador'])[1]/preceding::button[1]</value>
      <webElementGuid>2de1a986-99dc-40e6-b3ad-ce04113762d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Est. Consignado'])[1]/preceding::button[1]</value>
      <webElementGuid>24af706f-6eca-4055-99d6-2ab3f8ec2251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>286919ac-a07b-4927-b946-e1738df92715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d1b64e07-9609-49f4-8637-028e6aa8cec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnBuscarGuias' and (text() = 'Buscar' or . = 'Buscar')]</value>
      <webElementGuid>90f3937b-2002-4b43-ab9a-6aac9e99304e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
