<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Abrir_iframe_principal</name>
   <tag></tag>
   <elementGuidId>7e2b1194-6d9d-4dc1-a53e-be60b27dca2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframe_content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe_content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>62ce449f-8714-4339-b4d5-021bcb48b462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe_content</value>
      <webElementGuid>dde282ce-2983-4513-9542-e28d0fa7f116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframe_principal</value>
      <webElementGuid>fd8f5e29-f47c-4755-a00e-3e00b6774186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframeContentPrincipal</value>
      <webElementGuid>14a27fc8-0ec8-4059-8585-27fb38c0d02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.olva.pe/infoweb/sci/contenido/internacional/index.php/dashboard/cargarPrueba</value>
      <webElementGuid>7d4ef083-662e-4c1f-bcd3-c1ca27e29a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe_content&quot;)</value>
      <webElementGuid>43816bec-fbc9-457f-950c-3e02f0301ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe_content']</value>
      <webElementGuid>f235ca21-e6d6-4b1a-8e36-7e71beda6a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abrir'])[1]/following::iframe[1]</value>
      <webElementGuid>6fbab90c-fc40-4fa5-b0af-64e84518f7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internacional'])[1]/following::iframe[1]</value>
      <webElementGuid>80f6b2de-ac78-4858-a442-a88b9b40556c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize AdminLTE'])[1]/preceding::iframe[1]</value>
      <webElementGuid>d42d5b86-9942-4b44-a24b-02065a0c5e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Navbar border'])[1]/preceding::iframe[1]</value>
      <webElementGuid>7bce9f7a-1a54-44fd-807c-a8a9e7c05b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e5e934ab-b91f-4c0c-bd46-cc0202f43056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe_content' and @name = 'iframe_principal' and @src = 'https://www.olva.pe/infoweb/sci/contenido/internacional/index.php/dashboard/cargarPrueba']</value>
      <webElementGuid>7bae2e68-3f42-4b29-a7d9-0f656bf2db12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
