<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txt_usuario</name>
   <tag></tag>
   <elementGuidId>68e36441-3c36-4164-8c88-861b62f69bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_usuario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_usuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>305501a1-1d1b-462a-bba4-dc82548430d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bd67c6e-2fa0-47e3-a5d8-92bcee744017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e3987cde-d543-4932-90bc-831033b6df12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>7b28608a-4516-420b-a1da-1d832a850315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_usuario</value>
      <webElementGuid>062e3643-bb7b-4dd4-9ed8-a2989b07b7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_usuario</value>
      <webElementGuid>435314d5-148d-4c54-8989-1c76cc042957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_usuario&quot;)</value>
      <webElementGuid>18676759-36b9-4ed7-8dd3-ff0fdc837449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_usuario']</value>
      <webElementGuid>98853257-cd05-4e8a-aaf9-fd12dd020965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1c41caab-fbed-4dac-9bb7-80c94a32885d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Usuario' and @name = 'txt_usuario' and @id = 'txt_usuario']</value>
      <webElementGuid>c841c54b-c66f-4f5b-a4e0-cc6151b40258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
