<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VALID_ OK</name>
   <tag></tag>
   <elementGuidId>7103f384-8ecf-4eae-a7ad-3d1be847b042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;select2-estadoConsignado-result-dpeu-9005&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-estadoConsignado-result-xxtb-9005</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>93daac7a-6791-41f7-884d-6253f663252e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>5cf3a462-cf71-436d-aa3b-1fec27a56498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-xxtb-9005</value>
      <webElementGuid>1d910a26-e0d3-4de5-b208-008c945e473a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1c8280f8-3d8a-467e-9132-b2d13f6c1d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac5e649f-af40-40dc-83f4-217b127a6f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-estadoConsignado-result-xxtb-9005</value>
      <webElementGuid>4374a767-c2ec-4d21-a0c5-3c5f89e8eaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        VALIDADO OK                                                    </value>
      <webElementGuid>d1d44e29-86f1-4c36-937f-9d3ac589cc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-estadoConsignado-result-xxtb-9005&quot;)</value>
      <webElementGuid>cf238194-4891-43b1-881e-360754ab093a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id='select2-estadoConsignado-result-xxtb-9005']</value>
      <webElementGuid>76cbf2fa-c3dc-4024-8a07-67b2a204d8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-estadoConsignado-results']/li[2]</value>
      <webElementGuid>257aa3ec-0461-4ac2-a840-758aa09ef9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRADO'])[2]/following::li[1]</value>
      <webElementGuid>c6ecfb60-3e5d-496a-9bac-746024b511ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-estadoConsignado-result-xxtb-9005', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>d689633b-be41-4278-89e1-843e7d25e4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDADO ERROR'])[3]/preceding::li[1]</value>
      <webElementGuid>fc6e3ab6-df2c-486d-a68c-13831eeba929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CORREGIDO'])[15]/preceding::li[2]</value>
      <webElementGuid>604d4998-7430-4315-837a-b3f8f556ec6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[2]</value>
      <webElementGuid>4c1e7d46-71ee-4892-9f48-b93ba6f41df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-estadoConsignado-result-xxtb-9005' and (text() = '
                                                        VALIDADO OK                                                    ' or . = '
                                                        VALIDADO OK                                                    ')]</value>
      <webElementGuid>640f2771-f064-4486-a539-b0e92c09f226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
